version: '3.8'

services:
  app:
    build: .
    container_name: tata-business-bot
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Mount folder auth agar tidak perlu scan QR terus-menerus
      - ./.wwebjs_auth:/app/.wwebjs_auth